modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="concoction"
version="1.6.0"
displayName="Concoction"
displayURL="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
credits="Sebsish, woofyboo"
authors="Sebsish, woofyboo"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.concoction]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.concoction]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"




# Start of user code block dependencies configuration
[[mixins]]
config="concoction.mixins.json"
# End of user code block dependencies configuration
